# User provided contents:
#   - SRS domain
version: '2.4'

services:
  dovecot:
    image: lisnaz/dovecot:latest
    ports:
      # lmtp port
      - "24:24/tcp"
      # auth port
      - "11000:11000/tcp"
    volumes:
      - dovecot:/srv/dovecot
      - vmail:/srv/vmail
    environment:
      DOVECOT_PASSWORD_FILE_CONTENTS: |
        test@example.com:{SHA512-CRYPT}$6$9h3vBFtuxOdvEeZQ$uu6DpKaxZ9KX/IpR3TqGI9YkV/YVUKt9lTOLAlGrJs52rOvV.rvzmq5jtnnot02quvcDW5ii4.lmEEd/yJalm1

volumes:
  dovecot: {}
  vmail: {}
